from io_functions.input_functions import get_option_from_list
from io_functions.input_functions import get_yes_no_bool
from io_functions.file_reader import line_generator
from io_functions.view import console, print_md